name: Pull Request Check and Docker Image Heroku Deploy

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  prcheck:
    name: Pull Request Check
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 13.x
    
    - name: Install dependencies
      run: npm ci

    - run: npm audit

    - name: Build
      run: npm run build
      env:
        CI: true

  deploy:
    name: Deploy Docker Image to Heroku
    needs: prcheck
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.0.0
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "still-inlet-67918"
        heroku_email: "kumpiskunsk@gmail.com"
        dontuseforce: false
        usedocker: true

    
